# @vx/INFO: @vx/ci
name: bnd

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
  push:
    branches: [timeline, feat/vx-oss]
    paths:
      - ".github/workflows/bnd.yml"
      - ".changeset/**"
      - "packages/**"

concurrency:
  group: bnd-${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true
  # timeout-minutes: 10

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  REPO: ${{ github.repository || 'vezham/usehooks-ts' }} # inputs.GIT_REPO
  BRANCH: ${{ github.ref_name || 'timeline' }} # inputs.GIT_BRANCH

jobs:
  bnd:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: action | checkout | ${{ env.REPO }}@${{ env.BRANCH }}
        uses: vezham/vx-fe-deployer/.github/actions/common/setup-checkout@timeline
        with:
          GIT_REPO: ${{ env.REPO }}
          GIT_BRANCH: ${{ env.BRANCH }}

      - name: action | node & pnpm
        uses: vezham/vx-fe-deployer/.github/actions/common/setup-install-npm@timeline
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_VX_OSS }}

      - name: fork | build
        if: github.event_name == 'pull_request'
        # id: build
        continue-on-error: false
        shell: bash
        run: |
          cd packages/usehooks-ts
          pwd
          pnpm build || {
            echo "build failed with exit code $?"
            exit 1
          }

      - name: action | changesets/NPM-release
        uses: vezham/vx-fe-deployer/.github/actions/changesets/release@timeline
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_VX_OSS }}

      - name: ci-setup | LOG
        if: always()
        uses: vezham/vx-fe-deployer/.github/actions/common/log-artifact@timeline
